modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/JDKDigital/productive-bees/issues"

[[mods]] #mandatory
modId="productivebees"
version="${file.jarVersion}"
displayName="Productive Bees"
updateJSONURL="https://jdkdigital.cy/productivebees.json"
# displayURL="http://example.com/"
logoFile="logo.png"
credits="Thanks to me"
authors="LobsterJonn"
description='''
Useful bees
'''

[[dependencies.productivebees]] #optional
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.productivebees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
