modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId="productivebees"
version="${version}"
displayName="Productive Bees"
updateJSONURL="https://jdkdigital.cy/productivebees.json"
# displayURL="http://example.com/"
# logoFile="examplemod.png"
credits="Thanks to me"
authors="LobsterJonn"
description='''

'''

[[dependencies.productivebees]] #optional
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.productivebees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
