modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://github.com/JDKDigital/productive-bees/issues"
license="MIT"

[[mods]] #mandatory
modId="productivebees"
version="${file.jarVersion}"
displayName="Productive Bees"
updateJSONURL="https://jdkdigital.cy/productivebees.json"
# displayURL="http://example.com/"
logoFile="logo.png"
credits="Thanks to me"
authors="LobsterJonn"
description='''
Useful bees
'''

[[dependencies.productivebees]] #optional
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.productivebees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"
